language: c

compiler:
 - gcc
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y cmake gnuplot libfftw3-dev liblapack-dev gfortran libxml2-dev libgtk2.0-dev zlib1g-dev libreadline-dev libgtksourceview2.0-dev libgmp-dev curl libcurl4-openssl-dev libmpfr-dev flite1-dev libflite1 libopenmpi-dev mpi-default-bin mpi-default-dev r-base-dev libgomp1 libzzip-dev unixodbc-dev 
before_script: 
  - mkdir build
  - cd build
script: cmake .. && make
after_script:
  - ./simple_client

notifications:
  email:
    recipients:
    - arissynod@gmail.com
    on_success: change
    on_failure: always
