os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
language: 
  - c
cache: 
  - apt
compiler:
  - gcc
  - clang
before_install: 
  - . tools/ci/$TRAVIS_OS_NAME/before_install.sh
install:
  - . tools/ci/$TRAVIS_OS_NAME/install.sh
before_script: 
  - . tools/ci/$TRAVIS_OS_NAME/before_script.sh
script: 
  - . tools/ci/$TRAVIS_OS_NAME/script.sh
after_success:
  - . tools/ci/$TRAVIS_OS_NAME/after_success.sh
notifications:
  email:
    recipients:
    - arissynod@gmail.com
    on_success: change
    on_failure: always
