language: c

compiler:
 - gcc
 - clang
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y gnuplot libfftw3-dev liblapack-dev gfortran libxml2-dev libgtk2.0-dev zlib1g-dev libreadline-dev libgtksourceview2.0-dev libgmp-dev curl libcurl4-gnutls-dev libmpfr-dev flite1-dev libflite1 libopenmpi-dev mpi-default-bin mpi-default-dev r-base-dev libgomp1 libzzip-dev unixodbc-dev 
script: mkdir build && cd build && cmake .. && make

notifications:
  email:
    recipients:
    - arissynod@gmail.com
    on_success: change
    on_failure: always
